### ISSUE TITLE
`FluentValue::into_number` may cause issues with decimal conversions

### ISSUE THREAD

**Issue by kazimuth** [projectfluent/fluent-rs#92] opened 2019-02-25 21:16 UTC
```rust
impl FluentValue {
    pub fn into_number<S: ToString>(v: S) -> Result<Self, ParseFloatError> {
        f64::from_str(&v.to_string()).map(|_| FluentValue::Number(v.to_string()))
    }
    // ...
}
```

https://github.com/projectfluent/fluent-rs/blob/master/fluent-bundle/src/types.rs#L32

`f64` has limited precision which may not accurately represent an input number, for instance if I'm using a [`d128`](https://alkis.github.io/decimal/decimal/struct.d128.html) to represent currency.

It might be worth writing a custom parser that validates inputs are usable numbers without modifying them.

**Comment by alerque** [comment] 2024-05-06 11:14
This issue is a duplicate of #337 (and also #214). That issue is of course later than this one, but since it has some suggestions of a fix I think I'll close this version no discussion continues elsewhere. I would suggest subscribing to #337 if you want to be notified when this is fixed.

**Closed by alerque** 2024-05-06 11:14 UTC
Labels: enhancement, help wanted, design-decision, fluent-bundle
