### ISSUE TITLE
Include source position in the AST

### ISSUE THREAD

**Issue by wiiznokes** [projectfluent/fluent-rs#346] opened 2024-03-02 16:23 UTC
I'm creating a tool to check if there is more than two identifiers with the same name. How can i know where the error is in the file?

Idk what is the standard way of doing this, i'm thinking of providing a field `pos: Option<usize>`, inside the ast types, but i'm not sure.

wdyt?

**Comment by zbraniecki** [comment] 2024-03-10 02:40
Ugh, I understand what you're trying to achieve but the architecture is particularly not suited for that. We do not associate AST with any textual representation, and binding AST to offsets would do just that.

If you were able to achieve adding that without inducing performance, memory penalty or increasing AST maintenance complexity, I'd be open to that, but I'm concerned it won't be easy to do.

For your particular purpose, you could extend the parser to handle optional visitor/inspect callback before inserting an entry to the AST, and check if it's an ID that already has been added.
I know it's not perfect, but parser is tied to source format, resulting AST is not.

**Comment by wiiznokes** [comment] 2024-03-13 22:05
> For your particular purpose, you could extend the parser to handle optional visitor/inspect callback before inserting an entry to the AST, and check if it's an ID that already has been added.

while this could work, i'm also planning to do more verification like compare two files, so having to parse multiple times is not great.

I know it doesn't really fill the maintenance constraint but would a feature gate could be considered?

**Comment by zbraniecki** [comment] 2024-03-13 22:14
Sure, I'd like to just ask for a good design that minimizes the maintenance burden. I don't want to have each edit to AST/parser be slowed down by source position considerations.

Maybe a trait that can be implemented on each node and parser `#[cfg(...)]node.setPositionInSource(offset)` ?

**Comment by wiiznokes** [comment] 2024-03-14 00:09
But how will the offset be stored ?

I was thinking of something like `#[cfg(...)] pos: usize`, and then when parsing, we just need to insert the position `#[cfg(...)] pos: self.ptr`

To be clear, if the ast is changed, the positions will not be in sync, and the serializer will not take the offset into account.

**Comment by alerque** [comment] 2024-05-07 09:49
This seems to be a duplicate of #270.

**Closed by alerque** 2024-05-07 09:49 UTC
Labels: enhancement, crate:fluent-syntax
